package org.bukkit;

/**
 * Minimal stub of the Bukkit {@code Material} enum.
 *
 * <p>This intentionally covers only the most common materials needed for the
 * initial world/block/inventory API conformance work. Additional entries can
 * be appended without breaking existing code because enum order is stable.
 */
public enum Material {
    AIR,
    STONE,
    GRANITE,
    DIORITE,
    ANDESITE,
    DIRT,
    COARSE_DIRT,
    PODZOL,
    GRASS_BLOCK,
    SAND,
    RED_SAND,
    GRAVEL,
    WATER,
    LAVA,
    BEDROCK,
    COAL_ORE,
    IRON_ORE,
    GOLD_ORE,
    DIAMOND_ORE,
    EMERALD_ORE,
    REDSTONE_ORE,
    LAPIS_ORE,
    COPPER_ORE,
    COAL_BLOCK,
    IRON_BLOCK,
    GOLD_BLOCK,
    DIAMOND_BLOCK,
    EMERALD_BLOCK,
    REDSTONE_BLOCK,
    LAPIS_BLOCK,
    COPPER_BLOCK,
    OAK_LOG,
    OAK_PLANKS,
    OAK_LEAVES,
    GLASS,
    CHEST,
    FURNACE,
    CRAFTING_TABLE,
    STONE_PICKAXE,
    IRON_PICKAXE,
    DIAMOND_PICKAXE,
    STICK,
    COAL,
    IRON_INGOT,
    GOLD_INGOT,
    DIAMOND,
    REDSTONE,
    WHEAT_SEEDS,
    WHEAT,
    BREAD,
    APPLE,
    DIAMOND_SWORD,
    IRON_SWORD,
    STONE_SWORD,
    WOODEN_SWORD,
    PLAYER_HEAD,
    ZOMBIE_SPAWN_EGG,
    SKELETON_SPAWN_EGG,
    CREEPER_SPAWN_EGG;
}
